import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  alldocsSidebar: [
    'about',
    {
      type: 'category',
      label: '核心板',
      link: {
        type: 'generated-index',
        description: '核心板相关资料',
      },
      items: [{type: 'autogenerated', dirName: 'core-board'}],
    },
    {
      type: 'category',
      label: '主板',
      link: {
        type: 'generated-index',
        description: '主板相关资料',
      },
      items: [{type: 'autogenerated', dirName: 'mainboard'}],
    },
    {
      type: 'category',
      label: '直播机',
      link: {
        type: 'generated-index',
        description: '直播机相关资料',
      },
      items: [{type: 'autogenerated', dirName: 'live-machine'}],
    },
    'host-computing-box',
    'display-module',
   {
     type: 'category',
     label: '摄像头模组',
     collapsible: true,
     collapsed: true,
     link: {
       type: 'doc',
       id: 'camera-module/index',
     },
     items: [
       'camera-module/ov5695',
       'camera-module/ov13850',
       'camera-module/ov13855',
       'camera-module/imx415',
       'camera-module/imx766',
      ],
    },
   {
      type: 'category',
      label: '配件',
      collapsible: true,
      collapsed: true,
      link: {
       type: 'doc',
        id: 'accessories/index',
      },
      items: [
       'accessories/gps-module',
       'accessories/usb-to-ttl',
     ],
    },
	{
	  type: 'category',
	  label: '开发环境搭建',
	  collapsible: true,
	  collapsed: true,
	  link: {
	    type: 'generated-index',
	    title: '开发环境搭建',
	    description: 'VMware、Ubuntu、开发工具和 SDK 编译环境搭建文档。',
	  },
	  items: [
	    {
	      type: 'autogenerated',
	      dirName: 'development-environment-doc',
	    },
	  ],
	},
    {
      type: 'category',
      label: '开发板网盘',
      link: {
        type: 'generated-index',
        description: '开发板网盘资料',
      },
      items: [{type: 'autogenerated', dirName: 'development-board-netdisk'}],
    },
    {
      type: 'category',
      label: 'XSTAR官方文档',
      link: {
        type: 'generated-index',
        description: 'XSTAR Official Documents',
      },
      items: [{type: 'autogenerated', dirName: 'xstar-official-docs'}],
    },
    {
      type: 'category',
      label: '全志官方文档',
      link: {
        type: 'generated-index',
        description: 'Allwinner Official Documents',
      },
      items: [{type: 'autogenerated', dirName: 'allwinner-official-docs'}],
    },
    {
      type: 'category',
      label: '瑞芯微官方文档',
      link: {
        type: 'generated-index',
        description: 'Rockchip Official Documents',
      },
      items: [{type: 'autogenerated', dirName: 'rockchip-official-docs'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  alldocsSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
